
<!-- Script autogenerated by Svelte-Jinja (author: Dan Ellis) -->

<!-- Use templates folder to update -->


<main>
    <li class='accordion-item' aria-expanded={params.open}>

    <div class='accordion-item-header' on:click={handleToggle} tabindex="0" on:keyup={(e)=> (e.key === 'Enter' || e.keyCode === 13)?  handleToggle():null }>
        <slot name='header' />
    </div>

    <div class='accordion-item-body' use:collapse={params}>
        <slot name='body'  />
    </div>

    <slot/>

</li>
</main>


<script>
    import { getContext } from 'svelte'
import collapse from 'svelte-collapse'

export let key;
export let active = false;

const store = getContext('svelte-collapsible-accordion')
$: params = {
    open: active,
    duration: $store.duration,
    easing: $store.easing
}
function handleToggle() {
    if (params.open) {
        store.update(s => Object.assign(s, { key: null }))
        active = false
    }
    else {
        store.update(s => Object.assign(s, { key }))
        active = true
    }
}

</script>


<style>
    .accordion-item-header {
    user-select: none;
    cursor: pointer;
    /* height:100%; */
    display: block;
}

.accordion-item-body:focus input{
    min-height:300px;max-height:200%;

}

/* .parent:hover .child */

.accordion-item-body:hover input{
    min-height:300px;max-height:200%;

}
</style>
