
<!-- Script autogenerated by Svelte-Jinja (author: Dan Ellis) -->

<script>
    
import { Accordion } from 'svelte-collapsible'
import { default as AccordionItem } from './CustomAccordionItem.svelte' 


// export let items
export let key
export let all

let item = all[key]
</script>

<main>
    
<Accordion>
	<!-- 
	{ #each items as item }
	 -->
		<AccordionItem key={item.key} bind:active={item.active}>
			
			<div slot='header' class='header' >
				
				<span class='name'>{item.key}  </span>
				
                
                <h4 class='title' >{item.title}  </h4>
                
				<div class='icon' >{item.active?'^':'>'}</div>
			
			</div>
			
			<p slot='body' class='body'>
				{ item.text || '' }
            <slot>
                Content Pending.
            </slot>
			</p>

		</AccordionItem>
	
	<!-- { /each } -->

</Accordion>
</main>

<style>
    
	.name{
		margin-right: 4em;
		left:0;
		width:0em;
	}
	
	.title{
		margin-right: auto;
		margin-left: 0em;
		left:0;
	}
	

	.icon{
		margin-left: auto;
  	    order: 2;
		margin-right: 1em;
		color:steelblue;
		border-radius: 1px;
	}
	
	:global(.accordion) {
		width: 100%;
		max-width: 450px;
		margin: 0 auto;
	}
	
	:global(.accordion-item) {
		border-bottom: 1px solid rgb(100, 120, 140);
        /* border-top: 1px solid rgb(100, 120, 140); */

	}

	.header {
		display: flex;
		align-items: center;
		padding: 0.5em;
        height:1.5em;
	}
	

	.body {
		padding: 0.5em;
		margin: 0;
		font-size: 18px;
	}
</style>
