
<!-- Script autogenerated by Svelte-Jinja (author: Dan Ellis) -->

<!-- Use templates folder to update -->


<main>
    
<h2>Group</h2>
<Select items={complexItems} style='height:auto;' {groupBy}></Select>


<!-- <h2>Async</h2>
<Select {loadOptions} {optionIdentifier} {getSelectionLabel} {getOptionLabel} {Item} placeholder="Search for 🍺"></Select> -->
</main>


<script>
    import Select from 'svelte-select';

const complexItems = [
    {value: 'chocolate', label: 'Chocolate', group: 'Sweet'},
{value: 'pizza', label: 'Pizza', group: 'Savory'},
{value: 'cake', label: 'Cake', group: 'Sweet'},
{value: 'chips', label: 'Chips', group: 'Savory'},
{value: 'ice-cream', label: 'Ice Cream', group: 'Sweet'}
];

const groupBy = (item) => item.group;
const optionIdentifier = 'id';
const getOptionLabel = (option) => option.name;
const getSelectionLabel = (option) => option.name;
</script>


<style>
    .body{
    display:block;
}
</style>
