
<!-- Script autogenerated by Svelte-Jinja (author: Dan Ellis) -->

<!-- Use templates folder to update -->


<main>
    <div class="container">
    <span class="choose">{props.name}</span>

    <br>

    <div class="dropdown {expanded[props.menu] ? 'active': ''}">
        <div class="select" on:click='{toggle(props)}'>
            <span>{prp?prp.name:props.children[props.menu].name}</span>
            <i class="fa fa-chevron-left"></i>
        </div>
        <ul class="dropdown-menu  {expanded[props.menu] ? 'active': ''}">

            {#each props.children as child}
            <li id="{child.name}" children={child.children} on:click='{select(props.name,child.children,props.menu,child.name)}'>{child.name}</li>
            {/each}
        </ul>
    </div>

    <!-- secondary menue  -->
    {#if prp}
    <p> a {prp.name}</p>
    <svelte:self props={prp} bind:selected={selected}/> {/if} {#if props.type == 'group-radio'}
    <span class:expanded on:click={toggle} style="padding-left: 2.3em">
	<input type="radio" bind:group={selected} value={props} on:click={radioClick} />
	{props.name}
</span> {:else}
    <span on:click={toggle}>
	<span class='expanded'>'\e875'</span>{props.name}
    </span>
    {/if} {#if props.code && props.type != 'group-radio'}<small>({props.code})</small>{/if} {#if expanded}
    <ul>
        {#each props.children as child}
        <li>
            {#if child.type === 'group' || child.type === 'group-radio'}
            <svelte:self props={child} bind:selected={selected}/> {:else}
            <Radio props={child} bind:selected={selected}/> {/if}
        </li>
        {/each}
    </ul>
    {/if}


</div>
</main>


<script>
    import Radio from './Radio.svelte';

export let expanded;
export let props;
export let selected;
// export let prp;

expanded = false
prp = undefined
function radioClick(e) {
    e.stopPropagation();
}


function toggle (info){
    expanded = !expanded;
    console.log('toggle',info,expanded)
}

function select(name, info, num, infoname){
    console.log('loooggss',info,num,name,infoname)
    // document.getElementById(name).text = infoname
    // info.children.menu = +num+1
    info.name = infoname
    prp = info.children
    // toggle(num)
    console.log('hi')
    
    
    
    
}


</script>


<style>
    self{left:0}

span {
    position: relative;
    padding: 0 0 0 1.3em;
    /* background: '../icons/arrow.svg' 0 0.1em no-repeat; */
    /* content:'hello'; */
    background-size: 1em 1em;
    font-weight: bold;
    cursor: pointer;
}
/* span.icon{
    content:'hi'
} */

/* @font-face {
  font-family: entypo;
  src: url(Entypo.otf);
} */


/* ul {
    padding: 0.2em 0 0 0.5em;
    margin: 0 0 0 0.5em;
    list-style: none;
    border-left: 1px solid #eee;
}
li {
    padding: 0.2em 0;
}
input {
    position: absolute;
    top: 3px;
    left: 1.2em;
} */



/* New */
/* 
span.msg,
span.choose {
  color: #555;
  padding: 5px 0 10px;
  display: inherit
} */
.container {
  width: 500px;
  margin: 5px auto 0;
  text-align: center
}

/*Styling Selectbox*/
.dropdown {
  width: 300px;
  display: inline-block;
  background-color: #fff;
  border-radius: 2px;
  box-shadow: 0 0 2px rgb(204, 204, 204);
  transition: all .5s ease;
  position: relative;
  font-size: 14px;
  color: #474747;
  height: 100%;
  text-align: left
}
.dropdown .select {
    cursor: pointer;
    display: block;
    padding: 10px
}
.dropdown .select > i {
    font-size: 13px;
    color: #888;
    cursor: pointer;
    transition: all .3s ease-in-out;
    float: right;
    line-height: 20px
}
.dropdown:hover {
    box-shadow: 0 0 4px rgb(204, 204, 204)
}
.dropdown:active {
    background-color: #f8f8f8;

}
.dropdown.active:hover,
.dropdown.active {
    box-shadow: 0 0 4px rgb(204, 204, 204);
    border-radius: 2px 2px 0 0;
    background-color: #f8f8f8
}
.dropdown.active .select > i {
    transform: rotate(-90deg)
}
.dropdown .dropdown-menu {
    position: absolute;
    background-color: #fff;
    width: 100%;
    left: 0;
    margin-top: 1px;
    box-shadow: 0 1px 2px rgb(204, 204, 204);
    border-radius: 0 1px 2px 2px;
    overflow: hidden;
    display: none;
    max-height: 144px;
    overflow-y: auto;
    z-index: 9
}
.dropdown .dropdown-menu li {
    padding: 10px;
    transition: all .82s ease-in-out;
    cursor: pointer
} 
.dropdown .dropdown-menu {
    padding: 0;
    list-style: none
}

 .dropdown-menu .active{
    display:block;
    
} 


.dropdown .dropdown-menu li:hover {
    background-color: #f2f2f2
}
.dropdown .dropdown-menu li:active {
    background-color: #e2e2e2
}

</style>
